//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FleetManagementSystemApiWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FleetDetail
    {
        public int Id { get; set; }
        public string ModelName { get; set; }
        public string VehicleNumber { get; set; }
        public string DriverName { get; set; }
        public int DistanceTravelled { get; set; }
        public bool SufficientFuel { get; set; }
    }
}
